# Workflow for the Cyprus supermarkets scraping process

# Whenever pull request is made targeting branch initialisation, csv is reset
name: supermarkets-scraping

# Workflow's description
run-name: supermarkets scraping 

# Function to schedule the time (UTC), day, month, and year of the workflow process
#on:
#  schedule:
#    - cron: "31 09 * * *" #UTC time

on:
  pull_request:
#    # Sequence of patterns matched against refs/heads
    branches:
      - supermarkets-scraping
#      - supermarkets-scraping

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    steps:
      # It checks out the latest content of your repository
      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: Upgrade pip
        run: pip install --upgrade pip
      # Installs the required Python dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements_new.txt ]; then pip install --no-cache-dir -r requirements_new.txt; fi
      - name: Run ScrapingCode.py
        run: |
          python Supermarkets/ScrapingCode.py
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "supermarkets scraping completed"
          git push origin HEAD:main
